### ISSUE TITLE
Drawing error

### ISSUE THREAD

**Issue by khoriba** [robotoD/GenoVi#12]
Hi,
I am unable to get the diagram with the following error. The input file used is GBK format.
I believe the software has been successfully installed.

```
$ genovi -i annotation.gbk -s complete -cs paradice -bc white
/home/miniconda3/envs/genovi/lib/python3.7/site-packages/Bio/GenBank/Scanner.py:1219: BiopythonParserWarning: Premature end of file in sequence data
  "Premature end of file in sequence data", BiopythonParserWarning

GBK file transformed into faa succesfully. File saved as genovi-temp/contig_1-genovi.faa
output genovi-temp/contig_1-genovi

Deepnog prediction started

deepnog infer genovi-temp/contig_1-genovi.faa --out genovi-temp/contig_1-genovi_prediction_deepnog.csv -db cog2020 -t 1
[2023-08-02 09:02:14] deepnog.client.client - INFO - Starting deepnog
[2023-08-02 09:03:21] deepnog.client.client - INFO - Loading NN-parameters from /home/deepnog_data/cog2020/1/deepnog.pth ...
[2023-08-02 09:03:21] deepnog.client.client - INFO - Accessing dataset from genovi-temp/contig_1-genovi.faa ...
[2023-08-02 09:03:22] deepnog.client.client - INFO - Starting protein sequence group/family inference ...
[2023-08-02 09:03:22] deepnog.learning.inference - INFO - Inference device: cpu
deepnog inference: 2.46kseq [00:45, 53.5seq/s]
[2023-08-02 09:04:08] deepnog.learning.inference - INFO - Inference complete.
[2023-08-02 09:04:09] deepnog.client.client - INFO - Writing prediction to genovi-temp/contig_1-genovi_prediction_deepnog.csv
[2023-08-02 09:04:09] deepnog.client.client - INFO - All done.

Deepnog prediction finished succesfully. Predictions saved as genovi-temp/contig_1-genovi_prediction_deepnog.csv

/home/miniconda3/envs/genovi/lib/python3.7/site-packages/Bio/GenBank/Scanner.py:1219: BiopythonParserWarning: Premature end of file in sequence data
  "Premature end of file in sequence data", BiopythonParserWarning
genovi-temp/contig_1-genovi_bands.kar created succesfully.
genovi-temp/contig_1-genovi_tRNA_pos.txt created succesfully.
.
.
.
Transforming GenBank record sequence1.1 to .fna
Done
Drawing 1...
Traceback (most recent call last):
  File "/home/miniconda3/envs/genovi/bin/genovi", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/genovi/lib/python3.7/site-packages/scripts/GenoVi.py", line 685, in main
    visualiseGenome(*get_args())
  File "/home/miniconda3/envs/genovi/lib/python3.7/site-packages/scripts/GenoVi.py", line 382, in visualiseGenome
    os.rename("circos.svg", output_file + "-contig_" + str(i) + ".svg")
FileNotFoundError: [Errno 2] No such file or directory: 'circos.svg' -> 'genovi-contig_1.svg'

``` 

Thanks

**Comment by vsaona** [comment]
Well, yes, there seems to be an error.

Have you tried the test files to verify the installation is correct? This might happen if not every library is present.
If it works with other files, could you tell us more about this file you're trying to use? What's the source of it? What annotation software was used to create the file? Could you share the file itself?

**Comment by khoriba** [comment]
Sorry for my late reply.
I use Prokka for annotation for my bacteria strain. 
Sequencing data was processed by Fastq (for QC), Unicycler (using Illumina and Nanopore FQ).
