### ISSUE TITLE
Genovi installation problem

### ISSUE THREAD

**Issue by gaworj** [robotoD/GenoVi#18]
Hello,

Thank you for a really great tool.

I was able to install it on my laptop at home with Ubuntu 20.04 LTS but failed on Ubuntu workstations.

In the lab I'm using Ubuntu 20.04 LTS:
mamba 1.4.9
conda 23.5.2

and 16.04 LTS:
mamba 0.25.0
conda 4.14.0

When I tried to install with

 pip install genovi

Building wheels for collected packages: genovi
  Building wheel for genovi (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      scripts __init__.py
      #from .GenoVi import change_background, visualiseGenome, get_args, main
      #from .addText import addText
      #from .colors import parseColors
      #from .create_raw import getArgs, listdir_r, ends_sorted, create_kar, create_feature, base_complete, base, get_categories, create_kar_complete, create_feature_complete, new_loc, write_cog_files, write_lines, createRaw
      #from .createConf import create_conf, create_conf_main
      #from .GC_analysis import get_args_, write_content, generate_result, makeGC, createGC
      #from .genbank2faa import modify_locus, genbankToFaa, mainFaa
      #from .genbank2fna import gbkToFna, mainFna
      #from .mergeImages import mergeImages
      
      
      #__all__ = ['change_background', 'visualiseGenome', 'get_args', 'main', 'addText', 'parseColors', 'getArgs',
      #                   'listdir_r', 'ends_sorted', 'create_kar', 'create_feature', 'base_complete', 'base', 'get_categories',
      #                   'create_kar_complete', 'create_feature_complete', 'new_loc', 'write_cog_files', 'write_lines',
      #                   'createRaw', 'create_conf', 'create_conf_main', 'get_args_', 'write_content', 'generate_result',
      #                   'makeGC', 'createGC', 'modify_locus', 'genbankToFaa', 'mainFaa', 'gbkToFna', 'mainFna', 'mergeImages',
      #                   '__version__'
      #                   ]
      
      __version__ = '0.4.3'
      
      __all__ = ['__version__']
      
      /home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-76ctju7b/genovi_646f1292e06447638bfedfd88afa8d25/setup.py", line 88, in <module>
          'dev': extra_dev,
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 172, in setup
          ok = dist.parse_command_line()
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 475, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/dist.py", line 863, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 534, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
        File "<frozen importlib._bootstrap>", line 983, in _find_and_load
        File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 728, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/vendored/packaging/requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/vendored/packaging/_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/vendored/packaging/_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/vendored/packaging/specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/vendored/packaging/utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/vendored/packaging/tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/site-packages/wheel/vendored/packaging/_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "/home/jang/miniconda3/envs/genovi/lib/python3.7/functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for genovi
  Running setup.py clean for genovi
Failed to build genovi
ERROR: Could not build wheels for genovi, which is required to install pyproject.toml-based projects

Any hints?

Bests,
Jan

**Comment by cs-di05** [comment]
I am having the same issue
edit: I managed to install it with the latest python version. However, this raises another error #19

**Comment by vsaona** [comment]
Hi @gaworj , this `pip install genovi` was after creating and activating a conda enviroment with circos and Python 3.7?

**Comment by gaworj** [comment]
Hi, previously I have strictly followed the instructions and started from creating conda env before installing with pip.

Today I repeated the installation procedure in the fresh conda env and everything works fine...

Bests,
Jan
