### ISSUE TITLE
OSError: 'seaborn' is not a valid package style

### ISSUE THREAD

**Issue by cs-di05** [robotoD/GenoVi#19]
Hello

I am running Ubuntu 20.04 and installed genovi in a new conda environment with python=3.9 (as it did not work with version 3.7). However, when trying to open the help page I receive this error:

```
Traceback (most recent call last):
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/site-packages/matplotlib/__init__.py", line 866, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/site-packages/matplotlib/__init__.py", line 843, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cas/miniforge3/envs/genovi/bin/genovi", line 5, in <module>
    from scripts.GenoVi import main
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/site-packages/scripts/GenoVi.py", line 16, in <module>
    from .create_raw import getArgs, listdir_r, ends_sorted, create_kar, create_feature, base, get_categories, new_loc, write_cog_files, write_lines, postprocess
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/site-packages/scripts/create_raw.py", line 16, in <module>
    from .create_tables import cogs_classif
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/site-packages/scripts/create_tables.py", line 5, in <module>
    plt.style.use("seaborn")
  File "/home/cas/miniforge3/envs/genovi/lib/python3.12/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

``` 
How can I solve this? Thanks in advance
Cas

**Comment by cs-di05** [comment]
today I tried again in a new environment and it works
