### ISSUE TITLE
I got error when I run the tool 

### ISSUE THREAD

**Issue by Sam131992** [robotoD/GenoVi#20]
The following error I received when I run the tutorial 

(genovi) sam@DESKTOP-QP6LGUS:~$ genovi -i Paenibacillus.gbff -cs paradise --scale linear --alignment '<' -s complete
/home/sam/miniconda3/envs/genovi/lib/python3.7/site-packages/Bio/GenBank/Scanner.py:1219: BiopythonParserWarning: Premature end of file in sequence data
  "Premature end of file in sequence data", BiopythonParserWarning
'locus_tag'
Error when transforming gbk to faa.
genovi-temp/contig_1-genovi_bands.kar created succesfully.
genovi-temp/contig_1-genovi_tRNA_pos.txt created succesfully.
genovi-temp/contig_1-genovi_tRNA_neg.txt created succesfully.
genovi-temp/contig_1-genovi_rRNA_pos.txt created succesfully.
genovi-temp/contig_1-genovi_rRNA_neg.txt created succesfully.
Traceback (most recent call last):
  File "/home/sam/miniconda3/envs/genovi/bin/genovi", line 8, in <module>
    sys.exit(main())
  File "/home/sam/miniconda3/envs/genovi/lib/python3.7/site-packages/scripts/GenoVi.py", line 685, in main
    visualiseGenome(*get_args())
  File "/home/sam/miniconda3/envs/genovi/lib/python3.7/site-packages/scripts/GenoVi.py", line 341, in visualiseGenome
    sizes, cogs_p, cogs_n, lengths, chrms, hist, wanted_cogs = base(file, temp_folder + "/" + output_file_part, output_file + "/" + output_file, True, True, cogs_classified, cogs_classified, False, True, deepnog_confidence_threshold, verbose, wanted_cogs=wanted_cogs)
  File "/home/sam/miniconda3/envs/genovi/lib/python3.7/site-packages/scripts/create_raw.py", line 507, in base
    _ , _, chrms_cp, chrms_cn, hist = create_feature(gbk_file, tmp, output, sizes, "CDS", cogs_dict, verbose = verbose, complete=complete)
  File "/home/sam/miniconda3/envs/genovi/lib/python3.7/site-packages/scripts/create_raw.py", line 321, in create_feature    locus_tag = feature.qualifiers.get("locus_tag")[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by vsaona** [comment]
It looks like there's some kind of incompatibility between the file you are trying to read and the application.
Did you try with the files in "input_test" and did it work properly?
The Paenibacillus annotated genome is public? May I see it? If not, where did you get this file from? (Which tool did you use for annotation?)

**Comment by Sam131992** [comment]
I had annoted using kabse and galaxy tools, both is giving same results.
