### ISSUE TITLE
Python errors in running GenoVi

### ISSUE THREAD

**Issue by iwilkie** [robotoD/GenoVi#5]
Hi, 

I was hoping to try out GenoVi to visualise a few of my genomes, but have run into an issue I was hoping you could help me with.

From what I can tell there seem to be two different issues, one is something related to the cairoSVG library, which doesn't seem to be a major issue, whereas the other one actually stops the run and seems to be related to with the GenoVi python script itself. Here's the command I submitted and the output:

``` bash
$ genovi -i PROKKA_02082023.gbk -cs paradise -s complete --size --cogs_unclassified --title 'M30B9 sp.' --title_position top --italic_words 1 -te

There's been an error finding cairoSVG library, so PNG images might be different from expected. Please prefer using SVG output.
/Users/iwilkie/opt/anaconda3/envs/genovi/lib/python3.7/site-packages/Bio/GenBank/Scanner.py:1219: BiopythonParserWarning: Premature end of file in sequence data
  "Premature end of file in sequence data", BiopythonParserWarning
genovi-temp/contig_1-genovi_bands.kar created succesfully.
genovi-temp/contig_1-genovi_tRNA_pos.txt created succesfully.
genovi-temp/contig_1-genovi_tRNA_neg.txt created succesfully.
genovi-temp/contig_1-genovi_rRNA_pos.txt created succesfully.
genovi-temp/contig_1-genovi_rRNA_neg.txt created succesfully.
genovi-temp/contig_1-genovi_CDS_pos.txt created succesfully.
genovi-temp/contig_1-genovi_CDS_neg.txt created succesfully.
Transforming GenBank record LBDLHKHK_1 to .fna
Done
Drawing 1...
Traceback (most recent call last):
  File "/Users/iwilkie/opt/anaconda3/envs/genovi/bin/genovi", line 8, in <module>
    sys.exit(main())
  File "/Users/iwilkie/opt/anaconda3/envs/genovi/lib/python3.7/site-packages/scripts/GenoVi.py", line 685, in main
    visualiseGenome(*get_args())
  File "/Users/iwilkie/opt/anaconda3/envs/genovi/lib/python3.7/site-packages/scripts/GenoVi.py", line 414, in visualiseGenome
    pCDS_colour = CDS_positive, nCDS_colour = CDS_negative, tRNA_colour = tRNA, rRNA_colour = rRNA, GC_content_colour = GC_content, font_colour = font_colour)
  File "/Users/iwilkie/opt/anaconda3/envs/genovi/lib/python3.7/site-packages/scripts/addText.py", line 52, in addText
    source = open(inFile)
FileNotFoundError: [Errno 2] No such file or directory: 'genovi/genovi.svg'
``

Would you happen to have any recommendations for how to fix/avoid this issue, and how to go forward? 

I really appreciate any help you can provide, thanks in advance!

**Comment by vsaona** [comment]
Hi, this error probable means Circos could not generate the initial SVG image, because the input files didn't have expected format.
Is it possible for you to send me the Prokka-generated file you are using? Of course, it will be treated with strict confidentiality, used only for debugging purposes and deleted right afterwards.
Also, do the test cases work properly on your computer? It would be interesting to run test cases or some other GenBank file to fully check it is not a problem in your environment.

**Comment by iwilkie** [comment]
Hi @vsaona, thanks for the reply!

I've since tried a couple of things to no avail, but I think the issue might be the environment itself. Based on the error I was getting when I tried to run my file, I thought it might be a dependency issue, so I installed `cairosvg` in the environment.

<details>
<summary> Installing `cairosvg` in the `genovi` environment </summary>

(genovi) iwilkie@bigmem-3:~$ conda install -c conda-forge cairosvg
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.14.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /home/iwilkie/miniconda3/envs/genovi

  added / updated specs:
    - cairosvg


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cairo-1.16.0               |       hb05425b_4         1.4 MB
    cairocffi-1.4.0            |     pyhd8ed1ab_0          69 KB  conda-forge
    cairosvg-2.6.0             |     pyhd8ed1ab_0          42 KB  conda-forge
    cssselect2-0.2.1           |     pyh9f0ad1d_1          30 KB  conda-forge
    defusedxml-0.7.1           |     pyhd8ed1ab_0          23 KB  conda-forge
    glib-2.69.1                |       he621ea3_2         1.9 MB
    lcms2-2.12                 |       h3be6417_0         312 KB
    libwebp-1.2.4              |       h11a3e52_1          86 KB
    pillow-9.4.0               |   py37h6a678d5_0         721 KB
    python_abi-3.7             |          2_cp37m           4 KB  conda-forge
    tinycss2-1.2.1             |     pyhd8ed1ab_0          23 KB  conda-forge
    webencodings-0.5.1         |             py_1          12 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.6 MB

The following NEW packages will be INSTALLED:

  cairo              pkgs/main/linux-64::cairo-1.16.0-hb05425b_4
  cairocffi          conda-forge/noarch::cairocffi-1.4.0-pyhd8ed1ab_0
  cairosvg           conda-forge/noarch::cairosvg-2.6.0-pyhd8ed1ab_0
  cffi               conda-forge/linux-64::cffi-1.15.0-py37h036bc23_0
  cssselect2         conda-forge/noarch::cssselect2-0.2.1-pyh9f0ad1d_1
  defusedxml         conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
  giflib             conda-forge/linux-64::giflib-5.2.1-h36c2ea0_2
  glib               pkgs/main/linux-64::glib-2.69.1-he621ea3_2
  lcms2              pkgs/main/linux-64::lcms2-2.12-h3be6417_0
  libwebp            pkgs/main/linux-64::libwebp-1.2.4-h11a3e52_1
  libxcb             pkgs/main/linux-64::libxcb-1.15-h7f8727e_0
  pcre               conda-forge/linux-64::pcre-8.45-h9c3ff4c_0
  pillow             pkgs/main/linux-64::pillow-9.4.0-py37h6a678d5_0
  pixman             conda-forge/linux-64::pixman-0.40.0-h36c2ea0_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  python_abi         conda-forge/linux-64::python_abi-3.7-2_cp37m
  tinycss2           conda-forge/noarch::tinycss2-1.2.1-pyhd8ed1ab_0
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2023.01.10~ --> conda-forge::ca-certificates-2022.12.7-ha878542_0
  certifi            pkgs/main/linux-64::certifi-2022.12.7~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
lcms2-2.12           | 312 KB    | ########################################################################################################################################### | 100%
libwebp-1.2.4        | 86 KB     | ########################################################################################################################################### | 100%
defusedxml-0.7.1     | 23 KB     | ########################################################################################################################################### | 100%
cssselect2-0.2.1     | 30 KB     | ########################################################################################################################################### | 100%
cairo-1.16.0         | 1.4 MB    | ########################################################################################################################################### | 100%
cairocffi-1.4.0      | 69 KB     | ########################################################################################################################################### | 100%
cairosvg-2.6.0       | 42 KB     | ########################################################################################################################################### | 100%
python_abi-3.7       | 4 KB      | ########################################################################################################################################### | 100%
glib-2.69.1          | 1.9 MB    | ########################################################################################################################################### | 100%
tinycss2-1.2.1       | 23 KB     | ########################################################################################################################################### | 100%
webencodings-0.5.1   | 12 KB     | ########################################################################################################################################### | 100%
pillow-9.4.0         | 721 KB    | ########################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

</details>

I then ran the same command that I initially ran (shown in the first message of this issue), but got the same error.

Next, I ran the test case (I should've started here, I know, but I only spotted the file afterwards), which worked! I then ran the same command as the test case but with my own file (`genovi -i ../03.function/prokka/PROKKA_02082023.gbk -s draft -cs paradise --cogs_unclassified -bc white`), which also worked :) 

I then started adding flags I had initially tried, one try at a time, to figure out which one was causing the issue, and it seems to be related to the `--title_position top` flag. Since genovi generates `svg` files I don't really mind, but I thought I'd let you know.

Here's the output if I run the same command I was trying when I came across the error, except without the `--title_position top` flag (it works!):
```bash
(genovi) iwilkie@bigmem-3:/hpc-stage/iwilkie/isolate/06.genovi$ ls
(genovi) iwilkie@bigmem-3:/hpc-stage/iwilkie/isolate/06.genovi$ genovi -i ../03.function/prokka/PROKKA_02082023.gbk -cs paradise -s complete --size --cogs_unclassified --title 'M30B9 sp.' --italic_words 1 -te
/home/iwilkie/miniconda3/envs/genovi/lib/python3.7/site-packages/Bio/GenBank/Scanner.py:1219: BiopythonParserWarning: Premature end of file in sequence data
  "Premature end of file in sequence data", BiopythonParserWarning
genovi-temp/contig_1-genovi_bands.kar created succesfully.
genovi-temp/contig_1-genovi_tRNA_pos.txt created succesfully.
genovi-temp/contig_1-genovi_tRNA_neg.txt created succesfully.
genovi-temp/contig_1-genovi_rRNA_pos.txt created succesfully.
genovi-temp/contig_1-genovi_rRNA_neg.txt created succesfully.
genovi-temp/contig_1-genovi_CDS_pos.txt created succesfully.
genovi-temp/contig_1-genovi_CDS_neg.txt created succesfully.
Transforming GenBank record LBDLHKHK_1 to .fna
Done
Drawing 1...
Converting to png...
Converting to png...

WARNING! PNG version of image may look weird because italic text transformation is not yet properly implemented.
Please prefer using the svg version instead.

deleting temporary files
(genovi) iwilkie@bigmem-3:/hpc-stage/iwilkie/isolate/06.genovi$ ls
circos.svg  genovi
```

Thanks again for commenting, unfortunately I am not at liberty to share the `gbk` file I am working with, but let me know if you want me to try anything else to try and narrow down this problem further (e.g. sharing the `yml` file of the environment?)

**Comment by jsleavit** [comment]
I am having the same issue described above. I tried running the test case on a gbk file downloaded from the test genomes available here in this repository, and still get the same error. I tried installing cairosvg, but to no avail, the same error occurs. Might there be another solution?

**Comment by Svnipni** [comment]
I think Im having a similar albeit it different issue. Genovi seems to get stuck on my specific .gbk as it worked out of the box for a few of my other files. Sadly, this file in particular is one I especially wanted to see.

Here's the output:

```
....
Transforming Genbank record SAMPLE_542_3532 to .fna
Done
Drawing...
Converting to png...
Traceback (most recent call last):
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/xml/etree/ElementTree.py", line 1716, in close
    self.parser.Parse(b"", True) # end of data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.parsers.expat.ExpatError: no element found: line 3, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svni/mambaforge/envs/genovi/bin/genovi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/site-packages/scripts/GenoVi.py", line 685, in main
    visualiseGenome(*get_args())
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/site-packages/scripts/GenoVi.py", line 594, in visualiseGenome
    svg2png(bytestring = file.read(), write_to = output_file + "/" + output_file + ".png")
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/site-packages/cairosvg/surface.py", line 129, in convert
    tree = Tree(
           ^^^^^
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/site-packages/cairosvg/parser.py", line 390, in __init__
    tree = ElementTree.fromstring(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/site-packages/defusedxml/common.py", line 127, in fromstring
    return parser.close()
           ^^^^^^^^^^^^^^
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/xml/etree/ElementTree.py", line 1718, in close
    self._raiseerror(v)
  File "/home/svni/mambaforge/envs/genovi/lib/python3.11/xml/etree/ElementTree.py", line 1618, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 3, column 0
```

There seems to be a sudden end to my file? I'm not certain how to decipher this or how I could fix my .gbk file. Any help would be much appreciated.

Edit: The .gbk file that did work had considerably fewer contigs. 56 total, as opposed to the above 3532... So that was the culprit. Re-assembly from raw-reads and more stringent coverage parameters resulted in a new assembly with only 53 contigs and genovi worked!

**Comment by hvrxs** [comment]
Hello, I have a similar issue as well. This has come up when using both test files and my own genbank files. 

At first, I received this error message. 

```
Drawing 1...
Traceback (most recent call last):
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/bin/genovi", line 8, in <module>
    sys.exit(main())
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/scripts/GenoVi.py", line 685, in main
    visualiseGenome(*get_args())
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/scripts/GenoVi.py", line 369, in visualiseGenome
    change_background("none", False)
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/scripts/GenoVi.py", line 47, in change_background
    file = open(fileName)
FileNotFoundError: [Errno 2] No such file or directory: 'circos.svg'
```
Then I copied the circos.svg file from the example folder that comes along when installing genovi. When I ran the command again, it gave me the next error: 

``` 
Done
Drawing 1...
Converting to png...
Traceback (most recent call last):
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/xml/etree/ElementTree.py", line 1700, in close
    self.parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: unclosed token: line 1552, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/bin/genovi", line 8, in <module>
    sys.exit(main())
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/scripts/GenoVi.py", line 685, in main
    visualiseGenome(*get_args())
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/scripts/GenoVi.py", line 374, in visualiseGenome
    svg2png(bytestring = svgFile.read(), write_to = output_file + "-contig_" + str(i) + ".png")
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/cairosvg/surface.py", line 129, in convert
    tree = Tree(
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/cairosvg/parser.py", line 390, in __init__
    tree = ElementTree.fromstring(
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/site-packages/defusedxml/common.py", line 127, in fromstring
    return parser.close()
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/xml/etree/ElementTree.py", line 1702, in close
    self._raiseerror(v)
  File "/srv/scratch/z5259897/miniconda3/envs/genovi/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: unclosed token: line 1552, column 0
``` 

I'm suspecting this could be an installation issue on my end. Could someone help me troubleshoot please? 
Thanks.

**Comment by microbemarsh** [comment]
Same here, I really don't want to have to reassemble to visualize
